version: '3.8'
services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: password
      POSTGRES_DB: DatapolisX
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
volumes:
  pg_data:
